api = "0.2"

[buildpack]
id = "salesforce/nodejs-fn"
name = "Salesforce NodeJS Function Structured Middleware Buildpack"
version = "0.0.12"

[[stacks]]
id = "heroku-18"

[[stacks]]
id = "io.buildpacks.stacks.bionic"
